<Project>

    <PropertyGroup>
        <Authors>CoreDesign</Authors>
        <Company>CoreDesign</Company>
        <Copyright>Copyright (c) 2026 CoreDesign</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/coredesign/identity</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

</Project>
